name: build_windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: |
          cd src
          dir 'C:\Program Files\'
          dir 'C:\Program Files\Microsoft Visual Studio\'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Community'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin'
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\MSBuild.exe'
