name: build_linux

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Enable manual run from the Actions tab
  workflow_dispatch:

permissions:
  contents: read    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    

jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-20.04

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          pwd
          cd src
          chmod u+x ./build_linux.bash
          chmod u+x ./build_linux.py
          ./build_linux.bash
          #make -j LDFLAGS2=-static
          #file Linux/muscle | grep x86-64
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: muscle-linux-binary
          path: /home/runner/work/muscle/muscle/bin/muscle

  build-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/muscle"
        install: |
          apt-get update -q -y
          apt-get install -q -y make g++ file git python3
        run: |
          git config --global --add safe.directory /muscle
          cd /muscle  
          uname -a
          lscpu
          cd src/
          pwd
          chmod u+x ./build_linux.bash
          chmod u+x ./build_linux.py
          ./build_linux.bash
          #make -j LDFLAGS2=-static 
          #file Linux/muscle | grep aarch64

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: muscle-linux-aarch64-binary
        path: /muscle/bin/muscle
