name: build_windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: |
          cd src
          cmd /c '"C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\MSBuild.exe"' 'muscle.sln'  /p:Platform=x64 /p:Configuration=Release
